const header1= `Ratification of the Agreement`
const text1 = `* To be a member of the website of Talabat.com, first of all it is required that you fill in the registration form and then agree and undertake to comply with the provisions of the user agreement for Talabat.com. By filling in and ratifying the registration form or getting any services or ordering a meal using this system, the user agrees to be bound by the user agreement of Talabat.com Delivery Hero Egypt SAE.
* You are responsible for making all arrangements necessary for you to have access to the website. You are also responsible for ensuring that all persons who access the website through your Internet connection are aware of these website terms and that they comply with them. By viewing, using, accessing, browsing, or submitting any content or material on the site, you agree to these Terms of Use as a binding legal agreement between you and Talabat.com, without limitation or qualification. The term "you" or "You" shall refer to any person or entity, who views, uses, accesses, browses or submits any content or material to the site. If you do not agree to these Terms of Use, then you may not use the site. Talabat.com reserves the right to modify these Terms of Use at any time without prior notice. You agree that each visit you make to the sites shall be subject to the then-current Terms of Use, and continued use of the site now or following modifications in these Terms of Use confirms that you have read, accepted, and agreed to be bound by such modifications.
The terms and conditions apply to Talabat.com website and its associated applications on iPhone, iPad, Android, and mobile site platforms`
const header2= `Description of the Services`
const text2 = `Talabat.com allows its members who ratify the agreement to order from shops online.
Talabat.com provides a way for you to communicate your orders to delivery shops displayed on this website.
The purpose of this site is to provide a simple and convenient service to consumers, linking them to shops in their area that offer takeaway food. Interactive menus allow customers to build and submit orders at the click of a button.
We have created the website to serve as a food court online market. Talabat.com is a commercial service for food delivery online.
Talabat.com does not sell or interfere in any way in the production of any food produced at the shops. But what this online market offers to the users is only providing the ability to search for and find local shops that deliver or make food available to their addresses and enables ordering this food through this website. The shops are obligated to comply with country local laws, rules, regulations, and standards pertaining to food preparation, sale, marketing and safety.

However, it is important for users to understand that Talabat.com does not in any way independently verify the credentials, representations or products of shops, the ingredients or the quality of any products, or that a shop is in compliance with applicable laws. Buyers must make themselves comfortable through information provided by shops on the website or as requested by buyers directly from the shops as to the quality and reliability of the shops, as well as to their compliance with applicable laws.
Talabat.com does not in any way guaranty the quality of any food or that any food complies with applicable laws and does not guarantee matching the menu displayed on the site of what is actually provided to the users.
In addition, a shop may represent that food preparation is in accordance with special standards such as "organic," "macrobiotic" or allergen-specific standards such as "nut-free", "gluten-free", or "lactose-free". However, Talabat.com does not independently investigate or verify such representations.
Talabat.com shall not be liable or responsible for any food or services offered by shops that is unhealthy, is the cause of injury, that is otherwise unacceptable to buyers or that does not meet the expectation of buyers in any manner.
Buyers are solely responsible for verifying the accuracy of delivery addresses, and Talabat.com shall have no liability or responsibility for any such erroneous addresses. All food preparation and deliveries are the sole responsibility of the shop accepting the order. Please be aware that the shop will do everything they can to meet the delivery time specified, however delivery times may be affected by factors beyond their control and therefore cannot be guaranteed. We will inform you if we become aware of an unexpected delay.`
const header3= `How to make an order and how it is processed`
const text3 = `Once you have selected your order from the menu of your chosen Delivery shop you will be given the opportunity to submit your order by clicking on “Checkout” button. Please note it is important that you check the information that you enter and correct any errors before clicking on the “Checkout” button since once you click on this input errors cannot be corrected. On receipt of your order, Talabat.com will begin processing your order and we will send a message on the final page that your order has been received and sent successfully to the shop. Where any payment you make is not authorized you will be returned to the previous page on the website and we shall not be obliged to provide the services.`
const header4= `Order Cancellation`
const text4 = `You have the right to cancel an order up to 5 minutes from placing the order on our website.
While every effort is made to ensure that accurate pricing and descriptions are maintained, we reserve the right to cancel any order that is based on inaccurate information.

An order may be subsequently cancelled by a shop after you have received a confirmation that it has been sent to the shop. Talabat.com and our partner shops reserve the right to cancel any order, before or after acceptance, and will notify you immediately of any such cancellation.`
const header5= `Membership system for Talabat.com`
const text5 = `Any member of Talabat.com has a “user name” and “password” which are determined by the member herself/himself. The "user name" is personal to the member and the same “user name” is not given to two different members. The “password” is only known by the user. The user can change the password at any time. It is solely under the responsibility of the user to select and protect the password. Talabat.com is not liable for any problems, which may arise from the use of password. Talabat.com informs the user about the promotions, which take place in the user’s area and from which the user may benefit, by emails. Talabat.com does not share the user information with the third party companies – the phone number may be shared with the shop which deals with take-out foods, in order to provide a faster and correct delivery. For the user to connect to the services, which require a membership of Talabat.com, the user must enter the user name and password. This process is called “login” to Talabat.com.
By using this site, you warrant that any personal information provided by you is true, accurate, current and complete in all respects and that you will notify us immediately of any changes to your personal information by updating your member profile on the site or by contacting us, you agree not to impersonate any other person or entity or to use a false name or a name that you are not authorized to use.
You are not allowed to register multiple memberships for use by the same person. Violation of this clause may result in termination of your membership.
Members' passwords should be kept confidential at all times, and must not be shared or disclosed to anyone. You are responsible for all activities and orders that occur or are submitted through your membership. If you know or suspect that someone has knowledge of your password then you should contact us immediately.
You may not use the site for any unlawful or unauthorized purpose, including without limitation to:
Distributing any unlawful, libelous, abusive, threatening, harmful, obscene or otherwise objectionable material
Transmitting material that constitutes a criminal offense, results in civil liability or otherwise breaches any laws, regulations or codes of practice.
Interfering with any other persons use or enjoyment of the site.
Damaging, disabling or impairing the operation of this site or attempting to gain unauthorized access to this site or to networks connected to it, through hacking, spoofing or other such similar means.
We expect a device to hold one customer account only. We may allow service in such cases but we will not allow the use of promotions.`
const header6= `Responsibilities of the Member`
const text6 = `During the use of the services of Talabat.com, the member accepts and undertakes:
The information in the registration form is correct; in the conditions that this information is required the member is the only responsible for any losses which may arise from any misinformation or inadequate information (ex. forgetting the password); and in these cases his/her membership may be terminated.
The member is the sole responsible for all personal ideas, opinions, statements set forth by the member while using the services of Talabat.com, all the files uploaded to Talabat.com and the personal information sent, and that in no way Talabat.com shall be held liable for these files, not to access any services provided in Talabat.com unauthorized and in any way other that the one identified by Talabat.com; not to change the software in any way; not to use the software which is identified as being changed; and to indemnify Talabat.com for all material and moral losses in the event the member does not comply with the aforementioned articles, Talabat.com shall not be responsible for any damages which may arise from reading of data belonging to any members by any unauthorized people, not to send any messages which are threatening, immoral, racially and contrary to the Laws of Kuwait and international agreements, any correspondences, titles, nicknames posted to the context shall not be contrary to the rules of public morality, good manners and laws, not to harass and/or threaten other users, or any of Talabat.com live chat personnel, not to act in a way affecting the use of services by other users, not to post, print, distribute, circulate any amoral, inappropriate and unlawful materials and information which may give harm to the names of any people or institutions, not to advertise, sell or offer to sell any products or services, engage in any activities such as survey, competition or chain letter, not to send any information or programs which may give harm to the information or software in the computers of other users,
All of the records or materials obtained by using the services of Talabat.com are within the consent of the user; the user shall be absolutely responsible for any damages, loss of information or other losses caused by them in the user’s computer; the user shall not demand any compensation for any losses arising from the use of the service, not to use the services of Talabat.com.com for any commercial and advertising purposes without obtaining the consent of Talabat.com
Talabat.com may monitor all system at any time or continuously.
Talabat.com may use its system for commercial purposes, not to mail any information which is forbidden legally and circulate any mails which do not have authorization to be sent such as chain mail, malicious software, etc., not to record and misuse any personal information belonging to others, The member himself/herself is responsible for all kinds of acts made under the “username”, The clients must pay the service fee which is notified previously at the time of delivery of products; otherwise the products shall not be delivered to the clients. not to access the site or services using a third-party's account/registration without the express consent of the account holder; not to use the site for illegal purposes; not to commit any acts of infringement on the site or with respect to content on the site; not to use the site to engage in commercial activities apart from sanctioned use of Talabat services; not to copy any content, including, but not limited to shop menu content and third-party reviews, for republication in print or online; not to create shop reviews or blog entries for or with any commercial or other purpose or intent that does not in good faith comport with the purpose or spirit of the site; not to attempt to gain unauthorized access to other computer systems from or through the site; not to interfere with another person's use and enjoyment of the site or another entity's use and enjoyment of the site; not to upload or transmit viruses or other harmful, disruptive or destructive files; and/or

not to disrupt, interfere with, or otherwise harm or violate the security of the site, or any services, system resources, accounts, passwords, servers or networks connected to or accessible through the site or affiliated or linked sites (including those of our shop partners).
All users who are minors in the jurisdiction in which they reside (generally under the age of 18) must have the permission of, and be directly supervised by, their parent or guardian to use the website. If you are a minor, you must have your parent or guardian read and agree to this Agreement prior to you using the website.
Credit or Debit cards used in placing orders through the online payment gateway on Talabat.com website or applications must belong to the user. Otherwise, the user must attain the legal permission from the card owner to perform the transaction.`
const header7= `Visitor material and conduct`
const text7 = `Other than personally identifiable information, which is covered under the Talabat.com Privacy Policy, any material you transmit or post to this website will be considered non-confidential and non-proprietary. Talabat.com will have no obligations with respect to such material. Talabat.com and anyone we designate will be free to copy, disclose, distribute, incorporate and otherwise use that material and all data, images, sounds, text and other things embodied in it for any and all commercial or non-commercial purposes.
You are prohibited from posting, uploading or transmitting to or from this website any material that:
Breaches any applicable local, national or international law;
Is unlawful or fraudulent.
Amounts to unauthorized advertising; or
Contains viruses or any other harmful programs.
You may not misuse the website (including by hacking).
Any comments or feedback that you submit through the website must not:
Contain any defamatory, obscene or offensive material;
Promote violence or discrimination;
Infringe the intellectual property rights of another person;
Breach any legal duty owed to a third party (such as a duty of confidence);
Promote illegal activity or invade another’s privacy;
Give the impression that they originate from us; or
Be used to impersonate another person or to misrepresent your affiliation with another person.
The prohibited acts listed in the above paragraphs are non-exhaustive. You will pay Talabat for all costs and damages which it incurs as a result of you breaching any of these restrictions.
Talabat will fully co-operate with any law enforcement authorities or court order requesting or directing us to disclose the identity or location of anyone posting any material in breach of the above paragraph.`
const header8= `Talabat Go`
const text8 = `“Talabat Go” service is a mediator between the customer and the shop. If you have placed an order from Talabat Go shops, then a service fee will apply, as this will ensure the best service will be provided by the shop handling your order on your behalf and delivering your order to the location of your choice.`
const header9=`Refund Policy`
const text9 = `Talabat takes user satisfaction very seriously. In the case of problems with your food order, please contact Talabat through our live chat or call us on our hotline number and we will assist you. In appropriate cases, if you have already been billed by Talabat on behalf of the shp, Talabat will issue full or partial refunds. In the following cases: if you did not receive your order or received an incorrect order, you may be issued a full refund; if part of your order is missing, we may issue a partial refund. In every event, we will do our best to ensure your satisfaction.`
const header10= `Disclaimer`
const text10 = `THE INFORMATION, CONTENT, PRODUCTS, SERVICES, AND MATERIALS AVAILABLE THROUGH THE SITE (WHETHER PROVIDED BY TALABAT.COM, YOU, OTHER USERS OR OTHER AFFILIATES/THIRD PARTIES), INCLUDING WITHOUT LIMITATION, FOOD/BEVERAGE ORDERS, SUBMISSIONS, TEXT, PHOTOS, GRAPHICS, AUDIO FILES, VIDEO, AND LINKS, ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, TALABAT.COM DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, FREEDOM FROM COMPUTER VIRUS, AND IMPLIED WARRANTIES ARISING FROM COURSE OF DEALING OR COURSE OF PERFORMANCE`




export const viewTerms = [

    {text: text1, header: header1},
    {text: text2, header: header2},
    {text: text3, header: header3},
    {text: text4, header: header4},
    {text: text5, header: header5},
    {text: text6, header: header6},
    {text: text7, header: header7},
    {text: text8, header: header8},
    {text: text9, header: header9},
    {text: text10, header: header10},
]